### PR TITLE
User agent interceptor fix

### LINKED ISSUE #199: UserAgentInterceptor adds additional User-Agent header instead of adding a prefix to an already populated one
The expected behavior should be to take the populated header value and add a prefix with all the system and build information to it.

### PR DESCRIPTION
**Pull request by vcolin7**
Thanks for taking the time to contribute. Please take a moment to fill out the information below.

Fixes #199 & #200.

Changes Proposed in this pull request:
- Changed the intercept method to use header() instead of addHeader() so we only have one header named User-Agent at all times.
- Added checks and logic to make sure a user-provideed Application ID does not contain spaces and is not longer than 24 characters.
- Made additional changes to ensure user-provided values sdkName and sdkVersion are not included in the User Agent string when null.

### CODE REVIEW

File: sdk/core/azure-core/src/main/java/com/azure/android/core/http/interceptor/UserAgentInterceptor.java [hunk 1]
```diff
@@ -24,7 +25,8 @@
  * <a href="https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy">Azure Core: Telemetry policy</a>.
  */
 public class UserAgentInterceptor implements Interceptor {
-    private static final String USER_AGENT_HEADER = "User-Agent";
+    static final String USER_AGENT_HEADER = "User-Agent";
```
Comment (vcolin7) [inline sdk/core/azure-core/src/main/java/com/azure/android/core/http/interceptor/UserAgentInterceptor.java]: Made package-private since the unit test class will access this field.

File: sdk/core/azure-core/src/main/java/com/azure/android/core/http/interceptor/UserAgentInterceptor.java [hunk 2]
```diff
@@ -34,7 +36,7 @@
     // From the design guidelines, the application ID user agent header format is:
     // [<application_id>] azsdk-android-<client_lib>/<sdk_version> (<platform_info>; <application_info>;
     // <user_locale_info>
-    private static final String APPLICATION_ID_USER_AGENT_FORMAT = "[%s] " + USER_AGENT_FORMAT;
+    private static final String USER_AGENT_FORMAT_WITH_APPLICATION_ID = "[%s] %s";
```
Comment (vcolin7) [inline sdk/core/azure-core/src/main/java/com/azure/android/core/http/interceptor/UserAgentInterceptor.java]: Renamed in favor of clarity.
